Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Not Found: /favicon.ico
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 160, in login_view
    return render(request, 'login.html')
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Enter Valid Credentials
Enter Valid Credentials
Successfuly login
Successfuly login
Successfuly login
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Enter Valid Credentials
Successfuly login
Watching for file changes with StatReloader
Successfuly login
Watching for file changes with StatReloader
Successfuly login
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Successfuly login
Watching for file changes with StatReloader
Enter Valid Credentials
Enter Valid Credentials
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Successfuly login
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Successfuly login
Internal Server Error: /sentry-debug/
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 90, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/Converter/urls.py", line 24, in trigger_error
    division_by_zero = 1 / 0
ZeroDivisionError: division by zero
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sentry-debug/
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 90, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/Converter/urls.py", line 24, in trigger_error
    division_by_zero = 1 / 0
ZeroDivisionError: division by zero
Internal Server Error: /sentry-debug/
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 90, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/Converter/urls.py", line 24, in trigger_error
    division_by_zero = 1 / 0
ZeroDivisionError: division by zero
Internal Server Error: /sentry-debug/
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 90, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/Converter/urls.py", line 24, in trigger_error
    division_by_zero = 1 / 0
ZeroDivisionError: division by zero
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Enter Valid Credentials
Successfuly login
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/middleware.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/authapp/templatetags/custom_tags.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /temp_tag/
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 90, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 207, in temp_tag
    return render(request, "index.html", context)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/utils.py", line 1713, in runner
    return sentry_patched_function(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 105, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'modify_name'
Internal Server Error: /temp_tag/
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 90, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/views.py", line 207, in temp_tag
    return render(request, "index.html", context)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/utils.py", line 1713, in runner
    return sentry_patched_function(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 105, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'modify_name'
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (Permission denied): /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /favicon.ico
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (Permission denied): /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /favicon.ico
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /favicon.ico
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /favicon.ico
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /favicon.ico
Traceback (most recent call last):
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rishi/Desktop/File_converter/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 171, in __call__
    return f(*args, **kwargs)
  File "/home/rishi/Desktop/File_converter/Converter/authapp/custom_middleware/middlewares.py", line 25, in __call__
    raise PermissionDenied()
django.core.exceptions.PermissionDenied
Watching for file changes with StatReloader
Not Found: /favicon.ico
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
/home/rishi/Desktop/File_converter/Converter/Converter/settings/base.py changed, reloading.
Watching for file changes with StatReloader
